#cloud-config
disable_root: true
timezone: Europe/Moscow
package_update: true
package_upgrade: true

users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLU08AWIPAFQ0vfXU3AxHZbyIREoxA1POpxofHkVBT2Q+daDdCKswyu2etTCa0VAHu2NVWireQqKeYkS1oDQpz4J2KC0r97UIp61MZpocRX657YqVfWBXc7m679b9kPAXhIBZ1v9vdOl+nd0KgXstSKN7FCwQxq4XCAUe/0r62qF2PmYiNbYzay1vSmmJEgae3hLHnGrO3m3CfVsY4c13qqon1YdfLkiw4NaXZoNg8tWFu06mH9k+v/iSWXZago+8KQZQUrVR0cBGvM1uR4Bc4RHB3lX1FuU5M5W/hxkmDmN51U7OdNk9x6Srl058MfkYa0UcrhRDr+Ksv36NzQY4V user@notebook
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/rvibcQbrXf4UapimBbQxXEXcI+kuRu/elfg0mJqStUKW1+Gq1Yu5Uq/diZwAd1H2e+6Gpv49e1mLEJpnFzwboGv27ynEZRnNy6EVgv53lSYrxMDfpPIMqILz3Mmc678WEgZ7MmYFJOSUE9FwEwiu7PcoQU/ABobUzJYhGth2sk2h+gFIX6MHHCZV3nuOQSvw5FynnXXjylOPm1+xzsTaIq7IOiqaYI01TiogYJ5b8uhyDgabdGG30G4lurkY/BsrqhJ1WkcyWWei7Lxw2hQBb6n2qD3JdpEPr0iPZ4FUtWZjqzAbO06ki9L6S+mYSAZbQf+0sMfbQQSutg/pLihC8ux4B1kK319vVJ+n1qh1oW/+aCjtq7KXVkzvXKQ58VAhiImsuPJdOihdM5xo3OqeSZOEhSNR8rWYIOqtEnyhnC4ie/H+4lN8tOUE9UWyKZeHDBH89JdT0qsKNa5VOhnwEv5jA/NoP13ghRjtzYx5o4LXUlzDUxEIPzT/gn/7eDs= user@notebook