- hosts: nginx
  become: true
  tasks:

  - name: добавление ключа репозитория elasticsearch
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: D27D666CD88E42B4

  - name: добавление ключа репозитория nginx
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: ABF5BD827BD9BF62

  - name: добавление ключа репозитория zabbix
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 082AB56BA14FE591

  - name: добавление репозитория elasticsearch
    apt_repository:
      repo: deb https://mirror.yandex.ru/mirrors/elastic/8/ stable main
      state: present
      filename: elk

  - name: добавление репозитория nginx
    apt_repository:
      repo: deb http://nginx.org/packages/mainline/ubuntu jammy nginx
      state: present
      filename: nginx

  - name: добавление репозитория zabbix
    apt_repository:
      repo: deb https://repo.zabbix.com/zabbix/6.5/ubuntu jammy main
      state: present
      filename: zabbix

  - name: установка пакетов
    apt:
      pkg:
        - filebeat
        - nginx
        - zabbix-agent2

  - name: замена файла конфигурации filebeat
    template:
      src: template_filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root
      mode: '0600'

  - name: изменение файла конфигурации заббикс агента
    lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      regexp: '^Server=127.0.0.1'
      insertbefore: BOF
      line: 'Server=zabbix'

  - name: изменение файла конфигурации заббикс агента
    lineinfile:
      path: /etc/zabbix/zabbix_agent2.conf
      regexp: '^ServerActive=127.0.0.1'
      insertbefore: BOF
      line: ''

  - name: замена файла настроек ротации логов nginx
    template:
      src: template_logrotate_nginx
      dest: /etc/logrotate.d/nginx
      owner: root
      group: root
      mode: '0644' 

  - name: изменение прав на файл логов nginx
    file:
      path: /var/log/nginx/access.log
      mode: '0644'

  - name: изменение прав на файл логов nginx
    file:
      path: /var/log/nginx/error.log
      mode: '0644'

  - name: включение службы filebeat
    systemd:
      name: filebeat.service
      enabled: true
  
  - name: включение службы nginx
    systemd:
      name: nginx.service
      enabled: true
  
  - name: включение службы zabbix agent
    systemd:
      name: zabbix-agent2.service
      enabled: true

  - name: перезапуск службы filebeat
    systemd:
      state: restarted
      name: filebeat.service
  
  - name: перезапуск службы nginx
    systemd:
      state: restarted
      name: nginx.service
  
  - name: перезапуск службы zabbix agent
    systemd:
      state: restarted
      name: zabbix-agent2.service

  - name: включение модуля nginx для filebeat
    command: filebeat modules enable nginx

  - name: изменение настроек модуля nginx для filebeat
    lineinfile:
      path: /etc/filebeat/modules.d/nginx.yml
      regexp: '^    enabled: false'
      insertbefore: BOF
      line: '    enabled: true'     

  - name: замена файла настроек ротации логов nginx
    template:
      src: template_filebeat_nginx.yml
      dest: /etc/filebeat/modules.d/nginx.yml
      owner: root
      group: root
      mode: '0644' 

  - name: перезапуск службы filebeat
    systemd:
      state: restarted
      name: filebeat.service

  - name: инициализация filebeat
    command: filebeat setup