- hosts: zabbix
  become: true
  tasks:

  - name: добавление ключа репозитория nginx
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: ABF5BD827BD9BF62

  - name: добавление ключа репозитория postgresql
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 7FCC7D46ACCC4CF8

  - name: добавление ключа репозитория zabbix
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 082AB56BA14FE591
    
  - name: добавление репозитория nginx
    apt_repository:
      repo: deb http://nginx.org/packages/mainline/ubuntu jammy nginx
      state: present
      filename: nginx

  - name: добавление репозитория postgresql
    apt_repository:
      repo: deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main
      state: present
      filename: postgresql

  - name: добавление репозитория zabbix
    apt_repository:
      repo: deb https://repo.zabbix.com/zabbix/6.5/ubuntu jammy main
      state: present
      filename: zabbix

  - name: установка пакетов
    apt:
      pkg:
      - nginx
      - php8.1-pgsql
      - python3-psycopg2
      - postgresql
      - zabbix-agent2
      - zabbix-agent2-plugin-postgresql
      - zabbix-frontend-php
      - zabbix-nginx-conf
      - zabbix-server-pgsql
      - zabbix-sql-scripts
      - zabbix-web-service

  - name: изменение файла конфигурации веб сервера zabbix
    blockinfile:
      path: /etc/zabbix/web/zabbix.conf.php
      block: |
        <?php
        $DB['TYPE'] = 'POSTGRESQL';
        $DB['SERVER'] = 'localhost';
        $DB['DATABASE'] = 'zabbix';
        $DB['USER'] = 'zabbix';
        $DB['PASSWORD'] = 'zabbix';
      create: true
      mode: 0644
      owner: www-data
      group: www-data
  
  - name: установка русскоязычной локализации
    command: locale-gen ru_RU.UTF-8

  - name: удаление дефолтного файла конфигурации nginx
    file:
      path: /etc/nginx/conf.d/default.conf
      state: absent

  - name: добавление пользователя nginx в группу www-data
    command: usermod -a -G www-data nginx

  - name: замена файла конфигурации zabbix server
    template:
      src: template_zabbix_server.conf
      dest: /etc/zabbix/zabbix_server.conf
      owner: root
      group: root
      mode: '0600'

  - name: включение службы nginx
    systemd:
      name: nginx.service
      enabled: true
  
  - name: включение службы php-fpm
    systemd:
      name: php8.1-fpm.service
      enabled: true
  
  - name: включение службы postgresql
    systemd:
      name: postgresql.service
      enabled: true

  - name: включение службы zabbix agent
    systemd:
      name: zabbix-agent2.service
      enabled: true

  - name: включение службы zabbix server
    systemd:
      name: zabbix-server.service
      enabled: true
  
  - name: включение службы zabbix web service
    systemd:
      name: zabbix-web-service.service
      enabled: true

  - name: перезапуск службы nginx
    systemd:
      state: restarted
      name: nginx.service

  - name: перезапуск службы php-fpm
    systemd:
      state: restarted
      name: php8.1-fpm.service

  - name: изменение файла конфигурации postgresql
    lineinfile:
      path: /etc/postgresql/15/main/pg_hba.conf
      regexp: '^local   all             postgres                                peer'
      insertbefore: BOF
      line: 'local all postgres trust'

  - name: перезапуск службы postgresql
    systemd:
      state: restarted
      name: postgresql.service

  - name: создание пользователя zabbix в postgresql
    postgresql_user:
      name: zabbix
      password: SCRAM-SHA-256$4096:Cy04RcolIRtv49A0udVkkA==$t+OiJlDZ+af5jDJxJ686giUceedvGEQLzVYAF8saVXE=:hNs9jMHyAFFDPNW3t+OF0up/mYzPFqiz+SNdxr46lf8=
      state: present

  - name: создание БД zabbix
    postgresql_db:
      name: zabbix
      owner: zabbix

  - name: импортирование начальной схемы и данных в базу zabbix
    shell: sh -c 'zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix || /bin/true'
  
  - name: перезапуск службы zabbix agent
    systemd:
      state: restarted
      name: zabbix-agent2.service

  - name: перезапуск службы zabbix server
    systemd:
      state: restarted
      name: zabbix-server.service

  - name: перезапуск службы zabbix web service
    systemd:
      state: restarted
      name: zabbix-web-service.service
