- name: добавление ключа репозитория zabbix
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 082AB56BA14FE591

- name: добавление репозитория zabbix
  apt_repository:
    repo: deb https://repo.zabbix.com/zabbix/6.5/ubuntu jammy main
    state: present
    filename: zabbix

- name: установка пакета zabbix-agent2
  apt:
    name: zabbix-agent2
    update_cache: yes
    state: present

- name: изменение файла конфигурации заббикс агента
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^Server=127.0.0.1'
    insertbefore: BOF
    line: 'Server=zabbix'

- name: изменение файла конфигурации заббикс агента
  lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    regexp: '^ServerActive=127.0.0.1'
    insertbefore: BOF
    line: ''

- name: включение службы zabbix agent
  systemd:
    name: zabbix-agent2.service
    enabled: true

- name: перезапуск службы zabbix agent
  systemd:
    state: restarted
    name: zabbix-agent2.service